### ISSUE TITLE
InvalidArgumentError: Boxes contains at least one element that is not finite

### ISSUE THREAD

**Issue by khatchad** [Viredery/tf-eager-fasterrcnn#31]
During the "overfitting a sample" section, I get the following error after the batch processing:

```
...
('batch', 96, '-', 0.31591606)
('batch', 97, '-', 0.20713705)
('batch', 98, '-', 0.19917412)
('batch', 99, '-', 0.19703498)
Traceback (most recent call last):
  File "tf-eager-fasterrcnn/train_model.py", line 102, in <module>
    res = model.simple_test_bboxes(img, img_meta, proposals)
  File "detection/models/detectors/test_mixins.py", line 71, in simple_test_bboxes
    pooled_regions = self.roi_align(
  File "detection/models/roi_extractors/roi_align.py", line 87, in __call__
    pooled_rois.append(tf.image.crop_and_resize(
  File "tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Boxes contains at least one element that is not finite [Op:CropAndResize]
```

**Comment by khatchad** [comment]
BTW, this with the change from #28.
